# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Jupyter Book Template # Change this to your book title.
author: Mahmood Amintoosi # Change this to your name (or your team/organization name).
logo: docs/images/fum-cs-logo.png
copyright: "2025. CC0 Licensed - Computer Science Dept., Ferdowsi University of Mashhad"  # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: JB-tutorial.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - docs/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/fum-cs/jupyter-book-tutorial  # Online location of your book (change this to your GitHub repository link)
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: docs/images/fum-logo.ico
  extra_navbar: ""

# Add launch buttons
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    # This is to work around the bug of no syntax highlighting
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      # This is for plotly to work
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
